name: Upload Model to GitHub

on:
  push:
    branches:
      - main

jobs:
  upload_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git user
      run: |
        git config --global user.email "jaksa.marton@gmail.com"  # Set your email here
        git config --global user.name "marcilol"  # Set your name here

    - name: Set up Git LFS
      run: |
        git lfs install   # Install Git LFS
        git lfs track "*.pkl"  # Track all .pkl files with Git LFS

    - name: Pull latest changes
      run: git pull origin main  # Ensure latest changes are pulled

    - name: Add model file to Git LFS
      run: |
        git add .gitattributes  # Add the .gitattributes file
        git commit -m "Track model with Git LFS"
        git push origin main  # Push the changes to the repository

    - name: Upload model
      run: |
        git add models/readmission_model.pkl
        git commit -m "Add model file"
        git push https://marcilol:${{ secrets.GITHUB_TOKEN }}@github.com/marcilol/Healthcare_Daten.git
        # Replace USERNAME with your GitHub username and REPO with your repository name
